source_list:
  - SB
#  - OL
#  - ADDR
  - CP

SB:
  mysql_conf:
    partition_column: App_Transaction_Id
    query: "(select * from testdb.TRANSACTIONSYNC) as t"

OL:
  sftp_conf:
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data

ADDR:
  mongodb_config:
    database: addr
    collection: address

CP:
  s3_conf:
    s3_bucket: spark-faisal-spark
    staging_location: staging

s3_conf:
  s3_bucket: spark-faisal-spark
  staging_location: staging

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.TXN_FCT
  query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT

spark_sql_demo:
  agg_demo: >
    select
        AccountNumber,
        UniqueTransactionDescriptions,
        sort_array(UniqueTransactionDescriptions, false) as OrderedUniqueTransactionDescriptions,
        size(UniqueTransactionDescriptions) as CountOfUniqueTransactionTypes,
        array_contains(UniqueTransactionDescriptions, 'Movies') as WentToMovies
    from
        agg_finances


  case_when_demo: >
    select
        company,
        employee.firstName as firstName,
        case
            when company = 'FamilyCo' then 'Premium'
            when company = 'OldCo' then 'Legacy'
            else 'Standard'
        end as Tier
    from
        employees
