source_list:
#  - SB
#  - OL
#  - ADDR
#  - CP

target_list:
  - REGIS_DIM
  - CHILD_DIM
  - RTL_TXN_FCT

SB:
  mysql_conf:
    partition_column: App_Transaction_Id
    query: "(select * from testdb.TRANSACTIONSYNC) as t"

OL:
  sftp_conf:
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data

ADDR:
  mongodb_config:
    database: addr
    collection: address

CP:
  s3_conf:
    s3_bucket: spark-faisal-spark
    staging_location: staging

s3_conf:
  s3_bucket: spark-faisal-spark
  staging_location: staging

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.TXN_FCT
  query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT

REGIS_DIM:
  tableName: DATAMART.REGIS_DIM
  source_data:
    - CP
    - ADDR
  loadingQuery: >
    SELECT
      MONOTONICALLY_INCREASING_ID() AS REGIS_KEY, REGIS_CNSM_ID AS CNSM_ID,REGIS_CTY_CODE AS CTY_CODE,
      REGIS_ID, REGIS_DATE, REGIS_LTY_ID AS LTY_ID, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, Street, City, State, INS_DT
    FROM
      (SELECT
        DISTINCT REGIS_CNSM_ID, CAST(REGIS_CTY_CODE AS SMALLINT), CAST(REGIS_ID AS INTEGER),
        REGIS_LTY_ID, REGIS_DATE, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, ADDR.street as Street, ADDR.City as City, ADDR.state as State, CP.INS_DT as INS_DT
      FROM
        CP JOIN ADDR ON CP.REGIS_CNSM_ID = ADDR.consumer_id
      ) CP

#spark_sql_demo:
#  agg_demo: >
#    select
#        AccountNumber,
#        UniqueTransactionDescriptions,
#        sort_array(UniqueTransactionDescriptions, false) as OrderedUniqueTransactionDescriptions,
#        size(UniqueTransactionDescriptions) as CountOfUniqueTransactionTypes,
#        array_contains(UniqueTransactionDescriptions, 'Movies') as WentToMovies
#    from
#        agg_finances
#
#
#  case_when_demo: >
#    select
#        company,
#        employee.firstName as firstName,
#        case
#            when company = 'FamilyCo' then 'Premium'
#            when company = 'OldCo' then 'Legacy'
#            else 'Standard'
#        end as Tier
#    from
#        employees
